version: '3'

services:
  db:
    image: postgres
    hostname: localhost
    ports:
      - 5432
  www:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db