# Generated by Django 2.2.1 on 2019-05-08 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='last_updated',
            new_name='created',
        ),
        migrations.AddField(
            model_name='todo',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 21, 22, 57, 72577, tzinfo=utc)),
        ),
    ]
