# Generated by Django 2.2.1 on 2019-05-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0006_auto_20190508_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
