# Generated by Django 2.2.1 on 2019-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0007_auto_20190508_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_complated',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(choices=[(True, 'COMPLETED'), (False, 'NOT COMPLETED')], default=False),
        ),
    ]
