# Generated by Django 2.2.1 on 2019-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0008_auto_20190511_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(choices=[('COMPLETED', True), ('NOT COMPLETED', False)], default=False),
        ),
    ]
